export interface ContactSource {
  uri: string;
  domain: string;
}

export interface Contact {
  type?: string | null;
  email?: string | null;
  sources?: ContactSource[];
  twitter?: string | null;
  linkedin?: string | null;
  position?: string | null;
  full_name?: string | null;
  seniority?: string | null;
  department?: string | null;
  phone_number?: string | null;
  [key: string]: any;
}

export interface FundedCompany {
  id: string;
  source: string;
  company_name: string;
  domain?: string | null;
  funding_date?: string | null;       // ISO date string (YYYY-MM-DD)
  funding_stage?: string | null;
  funding_amount?: number | null;
  investors?: string[];
  contacts?: Contact[];
  social_media?: string[] | null;
  industry?: string | null;
  status: 'new' | 'contacted' | 'follow-up' | string;
  created_at: string;                 // ISO timestamp
}

// For inserting new rows (id & created_at generated by Supabase)
export type InsertFundedCompany = Omit<FundedCompany, 'id' | 'created_at'>;

// Filters for fetching companies
export interface CompanyFilters {
  search?: string;
  date_range?: 'week' | 'month' | 'quarter' | 'all';
  funding_stage?: string;
  industry?: string;
  status?: string;
}

// Dashboard stats
export interface DashboardStats {
  total_companies: number;
  this_week: number;
  total_funding: string;
  contacted: number;
}

// Waiting list
export interface WaitingListEntry {
  id: string;
  first_name: string;
  last_name: string;
  company_name: string;
  email: string;
  created_at: string;
}

// For inserting new waiting list entries
export type InsertWaitingListEntry = Omit<WaitingListEntry, 'id' | 'created_at'>;